### ISSUE TITLE
ERROR: Unauthorized to release this package

### ISSUE THREAD

**Issue by dysonance** [JuliaRegistries/Registrator.jl#214]
I installed the package and had it working about a month ago, but when trying to submit a new release for [Indicators.jl](https://github.com/dysonance/Indicators.jl/) I got the following:

![image](https://user-images.githubusercontent.com/4308994/63724837-bacfbe00-c826-11e9-90c0-652fdd3f94c6.png)

I have double-checked the installation and permissions:
![image](https://user-images.githubusercontent.com/4308994/63724927-fbc7d280-c826-11e9-9ef7-e3b35cb775bc.png)

**Comment by nkottary** [comment]
This is fixed in #213 . A new deployment will be made soon.

**Comment by PerezHz** [comment]
We're trying to register a new version of [Expect.jl](https://gitlab.com/wavexx/Expect.jl) on GitLab and both the owner of the repo and me (a collaborator with Reporter access) have tried to register it by following the instructions on pkg.julialang.org/registrator but keep getting the same "ERROR: Unauthorized to release this package". Would this be also fixed by #213?

**Comment by nkottary** [comment]
Yes, you can pull the latest.

**Comment by wavexx** [comment]
I still get the same issue while trying to register Expect.jl (as above). This is on gitlab.
registrator asks for "Read the authenticated user's personal information" only in my case.

**Comment by nkottary** [comment]
Is the repo private? If it is you will need to set this: https://github.com/JuliaRegistries/Registrator.jl/blob/24ba3a1cf2608c28b7e50d71ca4013bad320100c/run/config.web.toml#L17

**Comment by wavexx** [comment]
No, it is public:

https://gitlab.com/wavexx/Expect.jl

**Comment by nkottary** [comment]
@wavexx I've updated the change. Can you try registering now?

**Comment by wavexx** [comment]
On Sun, Sep 15 2019, Nishanth H. Kottary wrote:
> @wavexx I've updated the change. Can you try registering now?

Now the auth requests contains "API accesss".
I was able to get past the previous point.

I do get a JS error now (FF69 on linux):

18:07:18.358 SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON dataselect:184:19
    onload https://pkg.julialang.org/registrator/select:184

It worked on the second try:

https://github.com/JuliaRegistries/General/pull/3551

**Comment by nkottary** [comment]
We need API access to check whether you are a collaborator on the project. Registrator only allows collaborators to register a package.

**Comment by wavexx** [comment]
On Mon, Sep 16 2019, Nishanth H. Kottary wrote:
> We need API access to check whether you are a collaborator on the project. Registrator
> only allows collaborators to register a package.

I expected that.

My concern was that more on that random JSON error
